spring.application.name=vote

spring.datasource.url=jdbc:h2:file:./data/oh;INIT=CREATE SCHEMA IF NOT EXISTS oh
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

